os:
- linux
services:
- docker
language: node_js
node_js:
- 6.11.0
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - node
  - node_modules
  - "$HOME/.m2"
  - "$HOME/.yarn-cache"
env:
  global:
  - NODE_VERSION=6.11.0
  - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
  - SPRING_JPA_SHOW_SQL=false
before_install:
- jdk_switcher use oraclejdk8
- java -version
- sudo /etc/init.d/mysql stop
- sudo /etc/init.d/postgresql stop
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
install:
- yarn install
script:
- chmod +x mvnw
- "./mvnw clean test"
- yarn test
- "./mvnw package -Pprod -DskipTests"
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
deploy:
  provider: cloudfoundry
  username: amine.limouri@gmail.com
  password:
    secure: CsnfVLlAq2K5jJI7uzL9+uXxRTxOUdmCpzXeKph1ZhxypZwfUSpJf5asNajp5uKMnj7gz1qV+qU/rfHI83/D6IJEEkrtiaAXAu3rc8MWa+EJusw/GbEvnShRvH4tZ3AS9JO6PDFtu96LEYNnCa7uSy3Ic02TOVGwRD1BtqTCi9nkd1XDCY4ck3CGFkeFE4VK9yLCLXDtQTiS02/yFylFsPNKjPxsHBnAha2HUQa3h5iRVyuRA5/pmIHlm0Xr3F6qK8m/DL+Spsgyo9Tle6bC/gnDVwZMcElEdtXP/VCPqBo68E57xtCVEql8T6liHwPhZaPCD8R7uuaC44YqxLXLERfiGwmSvoP6vcPIvfDFNClMl537BvhlqBh53foZPrW0r1ie32woOCPq5TY5XmNgFClkSBAe1zuTSU95EOMmtZ23UPjflYfbtPuEErBvwMa/fo7oC5MPxM6Xh8bBo1TZN4uQl6D5yhGpHE/lACDO0DWLSPvUU6TFHfGwBAL9gi7g5/nQNG1CbQVNAQDwVhOOfv/h6q0QGOQ3JQ/FBoL2anF1R0zFzJ5yZjtaaBQcXHCDFumiPOd8DmrZ0ZxU2KVbuaNRp2/ppdzQXTsZwalJcpCJEcm1CTUBWIfmXj/vi3hDpsN7EiXB9VJBGw0qXkNlogXNXpULvHyW26QfmINXrBQ=
  api: https://api.run.pivotal.io
  organization: private-work-space
  space: development