version: '2'
services:
    myapp-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/MyApp/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
        ports:
            - 5432:5432
